local_development:
  adapter: mysql2
  database: ctgov_development
  username: ctgov
  password: ctgov_rocks
  host: localhost
  #socket: /cloudsql/ctgov-1152:ctgov

mysql_settings: &mysql_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: ctgov
  password: ctgov_rocks
  host: 173.194.241.193
  database: ctgov

ctgov_development:
  <<: *mysql_settings

development:
  <<: *mysql_settings

ctgov_production:
  <<: *mysql_settings

production:
  <<: *mysql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
