#development:
#  adapter: mysql2
#  database: ctgov
#  username: researcher
#  password: investigation
#  host: ctgov.cm871qfhg8vn.us-east-1.rds.amazonaws.com
#  port: 3306

productionxx:
  adapter: postgresql
  encoding: unicode
  database: aact_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  template: template0
  host: localhost
  pool: 5
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: dbcgh450g07q2j
  username: vwhojdpkvfmcdl
  password: 04UAcPjpia8YhaS8MPvCjawllB
  template: template0
  host: ec2-107-20-174-127.compute-1.amazonaws.com
  url: postgres://vwhojdpkvfmcdl:04UAcPjpia8YhaS8MPvCjawllB@ec2-107-20-174-127.compute-1.amazonaws.com:5432/dbcgh450g07q2j
  pool: 5
  port: 5432

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3


developmentxx:
  adapter: postgresql
  encoding: unicode
  database: aact_development
  pool: 5
  username: <%= ENV["DEV_DB_USERNAME"] %>
  password: <%= ENV["DEV_DB_PASSWORD"] %>
  template: template0
  host: localhost
  port: 5432
