development:
  adapter: mysql2
  database: ctgov_development
  username: root
  password: ukmfp2d!
  host: localhost

ctgov_development:
  adapter: mysql2
  database: ctgov_development
  username: root
  password: ukmfp2d!
  host: localhost

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

