resources:
- type: compute.v1.instance
  name: OpenTrials
  properties:
    zone: us-eastern1-b
    machineType: https://www.googleapis.com/compute/v1/projects/ctgov/zones/us-eastern1-b/machineTypes/f1-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-8-jessie-v20160119
    networkInterfaces:
      - network: https://www.googleapis.com/compute/v1/projects/ctgov-1152/global/networks/default
      # Access Config required to give the instance a public IP address
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
