class OldValidationCheck < ValidationCheck

	def self.table_prefix
		'clintrialsgov_out.'
	end

	def self.enumeration_specs
		[
		{:column_name=>'dispersion_type',		:table_name=>'results_outcome_analysis'},
		{:column_name=>'method',						:table_name=>'results_outcome_analysis'},
		{:column_name=>'arm_group_type',		:table_name=>'arm_groups'},
		{:column_name=>'assessment_type',		:table_name=>'clinical_study'},
		{:column_name=>'dispersion',				:table_name=>'RESULTS_BASELINE_MEASURES'},
		{:column_name=>'biospec_retention'	,:table_name=>'clinical_study'},
		{:column_name=>'category_title',		:table_name=>'REPORTED_EVENT_CTGY'},
		{:column_name=>'completion_date_type',:table_name=>'clinical_study'}
		{:column_name=>'ci_n_sides',				:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
		{:column_name=>'contact_type',			:table_name=>'central_contacts'},
		{:column_name=>'design_name',				:table_name=>'designs'},
		{:column_name=>'design_value',			:table_name=>'designs'},
		{:column_name=>'dispersion',				:table_name=>'RESULTS_OUTCOME_MEASURE'},
		{:column_name=>'enrollment_type',		:table_name=>'CLINICAL_STUDY'},
		{:column_name=>'event_type',				:table_name=>'REPORTED_EVENTS'},
		{:column_name=>'contact_type',			:table_name=>'FACILITY_CONTACTS'},
		{:column_name=>'gender',						:table_name=>'CLINICAL_STUDY'},
		{:column_name=>'healthy_volunteers',:table_name=>'CLINICAL_STUDY'},
		{:column_name=>'intervention_type',	:table_name=>'INTERVENTIONS'},
		{:column_name=>'measure_type',			:table_name=>'RESULTS_OUTCOME_MEASURE'},
		{:column_name=>'milestone_type',		:table_name=>'RESULTS_PARTFLOW_MLSTN'},
		{:column_name=>'dispersion_type',		:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
		{:column_name=>'overall_status',		:table_name=>'CLINICAL_STUDY'},
		{:column_name=>'param_type',				:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
		{:column_name=>'phase',							:table_name=>'CLINICAL_STUDY'},
		{:column_name=>'pi_employee',				:table_name=>'RESULTS_RESTRICTION_AGREEMENTS'},
		{:column_name=>'primary_completion_date_type',:table_name=>'CLINICAL_STUDY'},
		{:column_name=>'reference_type',		:table_name=>'REFERENCES'},
		{:column_name=>'responsible_party_type',:table_name=>'RESPONSIBLE_PARTIES'},
		{:column_name=>'outcome_type',			:table_name=>'RESULTS_OUTCOMES'},
		{:column_name=>'role',							:table_name=>'INVESTIGATORS'},
		{:column_name=>'safety_issue',			:table_name=>'STUDY_OUTCOME'},
		{:column_name=>'sampling_method',		:table_name=>'CLINICAL_STUDY'},
		{:column_name=>'sponsor_type',			:table_name=>'SPONSORS'},
		{:column_name=>'status',						:table_name=>'FACILITIES'},
		{:column_name=>'outcome_type',			:table_name=>'REsults_outcomes'},
		{:column_name=>'study_type',				:table_name=>'CLINICAL_STUDY'},
		{:column_name=>'safety_issue',			:table_name=>'study_outcome'}
		#',:table_name=>'INVESTIGATORS'},
		]
	end

	def self.col_width_specs
		[
			{:column_name=>'outcome_id',:table_name=>'STUDY_OUTCOME'},
			{:column_name=>'PMID',:table_name=>'REFERENCES'},
			{:column_name=>'acronym',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'affiliation',:table_name=>'INVESTIGATORS'},
			{:column_name=>'affiliation',:table_name=>'OVERALL_OFFICIALS'},
			{:column_name=>'agency',:table_name=>'SPONSORS'},
			{:column_name=>'agency_class',:table_name=>'SPONSORS'},
			{:column_name=>'agreement_id',:table_name=>'RESULTS_RESTRICTION_AGREEMENTS'},
			{:column_name=>'arm_group_id',:table_name=>'ARM_GROUPS'},
			{:column_name=>'arm_group_id',:table_name=>'REPORTED_EVENT_CTGY_GRP'},
			{:column_name=>'arm_group_id',:table_name=>'RESULTS_BASELINE_MEASURE_CATGY'},
			{:column_name=>'arm_group_id',:table_name=>'RESULTS_OUTCOME_ANALYSIS_GRP'},
			{:column_name=>'arm_group_id',:table_name=>'RESULTS_PARTFLOW_MLSTN_GRP'},
			{:column_name=>'arm_group_label',:table_name=>'ARM_GROUPS'},
			{:column_name=>'arm_group_label',:table_name=>'INTERVENTION_ARM_GROUPS'},
			{:column_name=>'arm_group_type',:table_name=>'ARM_GROUPS'},
			{:column_name=>'authority',:table_name=>'AUTHORITIES'},
			{:column_name=>'authority_id',:table_name=>'AUTHORITIES'},
			{:column_name=>'baseline_id',:table_name=>'RESULTS_BASELINE_MEASURES'},
			{:column_name=>'baseline_id',:table_name=>'RESULTS_BASELINE_MEASURE_CATGY'},
			{:column_name=>'baseline_measure_catgy_id',:table_name=>'RESULTS_BASELINE_MEASURE_CATGY'},
			{:column_name=>'baseline_measure_title',:table_name=>'RESULTS_BASELINE_MEASURES'},
			{:column_name=>'baseline_value',:table_name=>'RESULTS_BASELINE_MEASURE_CATGY'},
			{:column_name=>'biospec_descr',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'biospec_retention',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'brief_summary',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'brief_title',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'category_assessment',:table_name=>'REPORTED_EVENT_CTGY'},
			{:column_name=>'category_description',:table_name=>'REPORTED_EVENT_CTGY'},
			{:column_name=>'category_sub_title',:table_name=>'REPORTED_EVENT_CTGY'},
			{:column_name=>'category_title',:table_name=>'REPORTED_EVENT_CTGY'},
			{:column_name=>'category_title',:table_name=>'RESULTS_BASELINE_MEASURE_CATGY'},
			{:column_name=>'central_contact_id',:table_name=>'CENTRAL_CONTACTS'},
			{:column_name=>'ci_lower_limit',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'ci_n_sides',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'ci_percent',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'ci_upper_limit',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'ci_upper_limit_na_comment',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'citation',:table_name=>'REFERENCES'},
			{:column_name=>'city',:table_name=>'FACILITIES'},
			{:column_name=>'completion_date',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'completion_date_type',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'condition',:table_name=>'CONDITIONS'},
			{:column_name=>'condition_id',:table_name=>'CONDITIONS'},
			{:column_name=>'contact_type',:table_name=>'CENTRAL_CONTACTS'}
			{:column_name=>'contact_type',:table_name=>'FACILITY_CONTACTS'},
			{:column_name=>'country',:table_name=>'FACILITIES'},
			{:column_name=>'country',:table_name=>'LOCATION_COUNTRIES'},
			{:column_name=>'country',:table_name=>'REMOVED_COUNTRIES'},
			{:column_name=>'criteria',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'default_assessment',:table_name=>'REPORTED_EVENTS'},
			{:column_name=>'default_vocab',:table_name=>'REPORTED_EVENTS'}
			{:column_name=>'description',:table_name=>'ARM_GROUPS'},
			{:column_name=>'description',:table_name=>'INTERVENTIONS'},
			{:column_name=>'description',:table_name=>'LINKS'},
			{:column_name=>'description',:table_name=>'REPORTED_EVENTS'},
			{:column_name=>'description',:table_name=>'RESULTS_BASELINE_MEASURES'},
			{:column_name=>'description',:table_name=>'STUDY_OUTCOME'},
			{:column_name=>'design_id',:table_name=>'DESIGNS'},
			{:column_name=>'design_name',:table_name=>'DESIGNS'},
			{:column_name=>'design_value',:table_name=>'DESIGNS'},
			{:column_name=>'detailed_description',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'dispersion',:table_name=>'RESULTS_BASELINE_MEASURES'}
			{:column_name=>'dispersion',:table_name=>'RESULTS_OUTCOME_MEASURE'},
			{:column_name=>'dispersion_type',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'dispersion_value',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'download_date',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'download_date_dt',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'email',:table_name=>'CENTRAL_CONTACTS'},
			{:column_name=>'email',:table_name=>'FACILITY_CONTACTS'},
			{:column_name=>'email',:table_name=>'RESULTS_POINT_OF_CONTACT'},
			{:column_name=>'enrollment',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'enrollment_type',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'estimate_desc',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'event_type',:table_name=>'REPORTED_EVENTS'},
			{:column_name=>'events',:table_name=>'REPORTED_EVENT_CTGY_GRP'},
			{:column_name=>'facility_contact_id',:table_name=>'FACILITY_CONTACTS'},
			{:column_name=>'facility_id',:table_name=>'FACILITIES'},
			{:column_name=>'facility_id',:table_name=>'FACILITY_CONTACTS'},
			{:column_name=>'facility_id',:table_name=>'INVESTIGATORS'},
			{:column_name=>'facility_name',:table_name=>'FACILITIES'},
			{:column_name=>'firstreceived_date',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'firstreceived_results_date',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'frequency_threshold',:table_name=>'REPORTED_EVENTS'},
			{:column_name=>'gender',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'group_id',:table_name=>'ARM_GROUPS'},
			{:column_name=>'groups_desc',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'has_dmc',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'has_expanded_access',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'healthy_volunteers',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'int_arm_group_id',:table_name=>'INTERVENTION_ARM_GROUPS'},
			{:column_name=>'int_other_name_id',:table_name=>'INTERVENTION_OTHER_NAMES'},
			{:column_name=>'intervention_id',:table_name=>'INTERVENTIONS'},
			{:column_name=>'intervention_id',:table_name=>'INTERVENTION_ARM_GROUPS'},
			{:column_name=>'intervention_id',:table_name=>'INTERVENTION_OTHER_NAMES'},
			{:column_name=>'intervention_name',:table_name=>'INTERVENTIONS'},
			{:column_name=>'intervention_type',:table_name=>'INTERVENTIONS'},
			{:column_name=>'investigator_affiliation',:table_name=>'RESPONSIBLE_PARTIES'},
			{:column_name=>'investigator_full_name',:table_name=>'RESPONSIBLE_PARTIES'},
			{:column_name=>'investigator_id',:table_name=>'INVESTIGATORS'},
			{:column_name=>'investigator_title',:table_name=>'RESPONSIBLE_PARTIES'},
			{:column_name=>'is_fda_regulated',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'is_section_801',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'keyword',:table_name=>'KEYWORDS'},
			{:column_name=>'keyword_id',:table_name=>'KEYWORDS'},
			{:column_name=>'lastchanged_date',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'limitations_and_caveats',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'link_id',:table_name=>'LINKS'},
			{:column_name=>'location_countries_id',:table_name=>'LOCATION_COUNTRIES'},
			{:column_name=>'lower_limit',:table_name=>'RESULTS_BASELINE_MEASURE_CATGY'},
			{:column_name=>'masked_role',:table_name=>'DESIGNS'},
			{:column_name=>'maximum_age',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'measure',:table_name=>'STUDY_OUTCOME'},
			{:column_name=>'measure_description',:table_name=>'RESULTS_OUTCOME_MEASURE'},
			{:column_name=>'measure_type',:table_name=>'RESULTS_BASELINE_MEASURES'},
			{:column_name=>'measure_type',:table_name=>'RESULTS_OUTCOME_MEASURE'},
			{:column_name=>'mesh_condition_id',:table_name=>'CONDITION_BROWSE'},
			{:column_name=>'mesh_id',:table_name=>'MESH_THESAURUS'},
			{:column_name=>'mesh_intervention_id',:table_name=>'INTERVENTION_BROWSE'},
			{:column_name=>'mesh_seqid',:table_name=>'MESH_THESAURUS'},
			{:column_name=>'mesh_term',:table_name=>'CONDITION_BROWSE'},
			{:column_name=>'mesh_term',:table_name=>'INTERVENTION_BROWSE'},
			{:column_name=>'mesh_term',:table_name=>'MESH_THESAURUS'},
			{:column_name=>'method',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'method_desc',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'milestone_group_id',:table_name=>'RESULTS_PARTFLOW_MLSTN_GRP'},
			{:column_name=>'milestone_id',:table_name=>'RESULTS_PARTFLOW_MLSTN'},
			{:column_name=>'milestone_id',:table_name=>'RESULTS_PARTFLOW_MLSTN_GRP'},
			{:column_name=>'milestone_title',:table_name=>'RESULTS_PARTFLOW_MLSTN'},
			{:column_name=>'milestone_type',:table_name=>'RESULTS_PARTFLOW_MLSTN'},
			{:column_name=>'minimum_age',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'name_degree',:table_name=>'CENTRAL_CONTACTS'},
			{:column_name=>'name_degree',:table_name=>'FACILITY_CONTACTS'},
			{:column_name=>'name_degree',:table_name=>'INVESTIGATORS'},
			{:column_name=>'name_degree',:table_name=>'OVERALL_OFFICIALS'},
			{:column_name=>'name_or_title',:table_name=>'RESULTS_POINT_OF_CONTACT'},
			{:column_name=>'name_title',:table_name=>'RESPONSIBLE_PARTIES'},
			{:column_name=>'nct_alias',:table_name=>'NCT_ALIASES'},
			{:column_name=>'nct_alias_id',:table_name=>'NCT_ALIASES'},
			{:column_name=>'nct_id',:table_name=>'ARM_GROUPS'},
			{:column_name=>'nct_id',:table_name=>'AUTHORITIES'},
			{:column_name=>'nct_id',:table_name=>'CENTRAL_CONTACTS'},
			{:column_name=>'nct_id',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'nct_id',:table_name=>'CONDITIONS'},
			{:column_name=>'nct_id',:table_name=>'CONDITION_BROWSE'},
			{:column_name=>'nct_id',:table_name=>'DESIGNS'},
			{:column_name=>'nct_id',:table_name=>'FACILITIES'},
			{:column_name=>'nct_id',:table_name=>'FACILITY_CONTACTS'},
			{:column_name=>'nct_id',:table_name=>'INTERVENTIONS'},
			{:column_name=>'nct_id',:table_name=>'INTERVENTION_ARM_GROUPS'},
			{:column_name=>'nct_id',:table_name=>'INTERVENTION_BROWSE'},
			{:column_name=>'nct_id',:table_name=>'INTERVENTION_OTHER_NAMES'},
			{:column_name=>'nct_id',:table_name=>'INVESTIGATORS'},
			{:column_name=>'nct_id',:table_name=>'KEYWORDS'},
			{:column_name=>'nct_id',:table_name=>'LINKS'},
			{:column_name=>'nct_id',:table_name=>'LOCATION_COUNTRIES'},
			{:column_name=>'nct_id',:table_name=>'NCT_ALIASES'},
			{:column_name=>'nct_id',:table_name=>'OVERALL_OFFICIALS'},
			{:column_name=>'nct_id',:table_name=>'REFERENCES'},
			{:column_name=>'nct_id',:table_name=>'REMOVED_COUNTRIES'},
			{:column_name=>'nct_id',:table_name=>'REPORTED_EVENTS'},
			{:column_name=>'nct_id',:table_name=>'RESPONSIBLE_PARTIES'},
			{:column_name=>'nct_id',:table_name=>'RESULTS_BASELINE'},
			{:column_name=>'nct_id',:table_name=>'RESULTS_OUTCOMES'},
			{:column_name=>'nct_id',:table_name=>'RESULTS_PARTIC_FLOWS'},
			{:column_name=>'nct_id',:table_name=>'RESULTS_POINT_OF_CONTACT'},
			{:column_name=>'nct_id',:table_name=>'RESULTS_RESTRICTION_AGREEMENTS'},
			{:column_name=>'nct_id',:table_name=>'SECONDARY_IDS'},
			{:column_name=>'nct_id',:table_name=>'SPONSORS'},
			{:column_name=>'nct_id',:table_name=>'STUDY_OUTCOME'},
			{:column_name=>'non_inferiority',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'non_inferiority_desc',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'number_of_arms',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'number_of_groups',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'official_title',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'org_study_id',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'organization',:table_name=>'RESPONSIBLE_PARTIES'},
			{:column_name=>'organization',:table_name=>'RESULTS_POINT_OF_CONTACT'},
			{:column_name=>'other_name',:table_name=>'INTERVENTION_OTHER_NAMES'},
			{:column_name=>'outcome_description',:table_name=>'RESULTS_OUTCOMES'},
			{:column_name=>'outcome_id',:table_name=>'RESULTS_OUTCOMES'},
			{:column_name=>'outcome_id',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'outcome_id',:table_name=>'RESULTS_OUTCOME_MEASURE'},
			{:column_name=>'outcome_measure_id',:table_name=>'RESULTS_OUTCOME_MEASURE'}
			{:column_name=>'outcome_measure_id',:table_name=>'RESULTS_OUTCOME_MEASURE_CTGY'}
			{:column_name=>'outcome_measure_title',:table_name=>'RESULTS_OUTCOME_MEASURE'}
			{:column_name=>'outcome_title',:table_name=>'RESULTS_OUTCOMES'},
			{:column_name=>'outcome_type',:table_name=>'RESULTS_OUTCOMES'},
			{:column_name=>'outcome_value',:table_name=>'RESULTS_OUTCOME_MEASURE_CTGY'},
			{:column_name=>'overall_official_id',:table_name=>'OVERALL_OFFICIALS'},
			{:column_name=>'overall_status',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'p_value',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'p_value_desc',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'param_type',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'param_value',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'partflow_count',:table_name=>'RESULTS_PARTFLOW_MLSTN_GRP'},
			{:column_name=>'participant_description',:table_name=>'RESULTS_PARTFLOW_MLSTN_GRP'},
			{:column_name=>'participant_flow_id',:table_name=>'RESULTS_PARTFLOW_MLSTN'},
			{:column_name=>'participant_flow_id',:table_name=>'RESULTS_PARTIC_FLOWS'},
			{:column_name=>'period_title',:table_name=>'RESULTS_PARTIC_FLOWS'},
			{:column_name=>'phase',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'phone',:table_name=>'CENTRAL_CONTACTS'},
			{:column_name=>'phone',:table_name=>'FACILITY_CONTACTS'},
			{:column_name=>'phone',:table_name=>'RESULTS_POINT_OF_CONTACT'},
			{:column_name=>'phone_ext',:table_name=>'CENTRAL_CONTACTS'},
			{:column_name=>'phone_ext',:table_name=>'FACILITY_CONTACTS'},
			{:column_name=>'pi_employee',:table_name=>'RESULTS_RESTRICTION_AGREEMENTS'},
			{:column_name=>'point_of_contact_id',:table_name=>'RESULTS_POINT_OF_CONTACT'},
			{:column_name=>'population',:table_name=>'RESULTS_BASELINE'},
			{:column_name=>'population',:table_name=>'RESULTS_OUTCOMES'},
			{:column_name=>'posting_date',:table_name=>'RESULTS_OUTCOMES'},
			{:column_name=>'pre_assignment_details',:table_name=>'RESULTS_PARTIC_FLOWS'},
			{:column_name=>'primary_completion_date',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'primary_completion_date_type',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'recruitment_details',:table_name=>'RESULTS_PARTIC_FLOWS'},
			{:column_name=>'reference_id',:table_name=>'REFERENCES'},
			{:column_name=>'reference_type',:table_name=>'REFERENCES'},
			{:column_name=>'removed_countries_id',:table_name=>'REMOVED_COUNTRIES'},
			{:column_name=>'reported_event_category_id',:table_name=>'REPORTED_EVENT_CTGY'},
			{:column_name=>'reported_event_category_id',:table_name=>'REPORTED_EVENT_CTGY_GRP'},
			{:column_name=>'reported_event_catgy_grp_id',:table_name=>'REPORTED_EVENT_CTGY_GRP'},
			{:column_name=>'reported_event_id',:table_name=>'REPORTED_EVENTS'},
			{:column_name=>'reported_event_id',:table_name=>'REPORTED_EVENT_CTGY'},
			{:column_name=>'responsible_party_id',:table_name=>'RESPONSIBLE_PARTIES'},
			{:column_name=>'responsible_party_type',:table_name=>'RESPONSIBLE_PARTIES'},
			{:column_name=>'restrictive_agreement',:table_name=>'RESULTS_RESTRICTION_AGREEMENTS'},
			{:column_name=>'results_outcome_anal_grp_id',:table_name=>'RESULTS_OUTCOME_ANALYSIS_GRP'},
			{:column_name=>'results_outcome_analysis_id',:table_name=>'RESULTS_OUTCOME_ANALYSIS'},
			{:column_name=>'results_outcome_analysis_id',:table_name=>'RESULTS_OUTCOME_ANALYSIS_GRP'},
			{:column_name=>'role',:table_name=>'INVESTIGATORS'},
			{:column_name=>'role',:table_name=>'OVERALL_OFFICIALS'},
			{:column_name=>'rslts_baseline_id',:table_name=>'RESULTS_BASELINE'},
			{:column_name=>'rslts_baseline_id',:table_name=>'RESULTS_BASELINE_MEASURES'},
			{:column_name=>'safety_issue',:table_name=>'RESULTS_OUTCOMES'},
			{:column_name=>'safety_issue',:table_name=>'STUDY_OUTCOME'},
			{:column_name=>'sampling_method',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'sec_id',:table_name=>'SECONDARY_IDS'},
			{:column_name=>'secondary_id',:table_name=>'SECONDARY_IDS'},
			{:column_name=>'source',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'sponsor_id',:table_name=>'SPONSORS'},
			{:column_name=>'sponsor_type',:table_name=>'SPONSORS'},
			{:column_name=>'spread',:table_name=>'RESULTS_BASELINE_MEASURE_CATGY'},
			{:column_name=>'spread',:table_name=>'RESULTS_OUTCOME_MEASURE_CTGY'},
			{:column_name=>'start_date',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'state',:table_name=>'FACILITIES'},
			{:column_name=>'status',:table_name=>'FACILITIES'},
			{:column_name=>'study_design',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'study_outcomes_type',:table_name=>'STUDY_OUTCOME'},
			{:column_name=>'study_pop',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'study_rank',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'study_type',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'subjects_affected',:table_name=>'REPORTED_EVENT_CTGY_GRP'},
			{:column_name=>'subjects_at_risk',:table_name=>'REPORTED_EVENT_CTGY_GRP'},
			{:column_name=>'target_duration',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'time_frame',:table_name=>'REPORTED_EVENTS'},
			{:column_name=>'time_frame',:table_name=>'RESULTS_OUTCOMES'},
			{:column_name=>'time_frame',:table_name=>'STUDY_OUTCOME'},
			{:column_name=>'unit_of_measure',:table_name=>'RESULTS_OUTCOME_MEASURE'},
			{:column_name=>'units_of_measure',:table_name=>'RESULTS_BASELINE_MEASURES'},
			{:column_name=>'upper_limit',:table_name=>'RESULTS_BASELINE_MEASURE_CATGY'},
			{:column_name=>'upper_limit',:table_name=>'RESULTS_OUTCOME_MEASURE_CTGY'},
			{:column_name=>'url',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'url',:table_name=>'LINKS'},
			{:column_name=>'verification_date',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'why_stopped',:table_name=>'CLINICAL_STUDY'},
			{:column_name=>'zip',:table_name=>'FACILITIES'}
		]
	end

end
